apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-demo
  ports:
    - port: 80
      targetPort: 8080 # this is the port on which our application is running(this also become container port)
      nodePort: 30007